# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: true
dist: trusty
# services:
#   - docker

cache: 
  apt: true
  ccache: true
  packages: true
  directories:
    - $HOME/.ccache
    - $HOME/.m2


language: r
latex: false
r_build_args: '--no-build-vignettes'

after_success:
  - Rscript -e 'covr::codecov()'
  
env:
  - RGL_USE_NULL=TRUE
  
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      r:
        - oldrel
        - release
        - devel
    - os: osx
      osx_image: xcode10.2
      r: release
      env:
        - CC=clang
        - CXX=clang++

before_install:
  - eval "${MATRIX_EVAL}"
  - echo -e "#\x21/bin/sh\n\$1 &\nPROCESS=\"\$!\"\nwhile :\ndo\n  RESULT=\`ps -p \${PROCESS} -o comm=\`" > wait4.sh
  - echo -e "  if [ -z \"\${RESULT}\" ]; then\n    wait \${PROCESS}; exit \$?\n  else\n    echo \"-\"; sleep 10\n  fi\ndone\nexit \$?" >> wait4.sh
  # - more wait4.sh
  - echo -e "Package\x3A mnb_bnm" > DESCRIPTION
  - chmod 755 wait4.sh
