# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  
r:
  - oldrel
  - release
  - devel
  
before_install:
  - sudo apt-get install libfreetype6-dev 
  - sudo apt-get install libftgl-dev
  - sudo apt-get install mesa-common-dev 
  - sudo apt-get install libglu1-mesa-dev
  
env:
  - RGL_USE_NULL=TRUE
  
matrix:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode7.3
  