# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: true
dist: trusty
# services:
#   - docker

#cache: 
#  apt: true
#  ccache: true
#  packages: true
#  directories:
#    - $HOME/.ccache
#    - $HOME/.m2


language: r
latex: false

after_success:
  - Rscript -e 'covr::codecov()'
  
env:
  - RGL_USE_NULL=TRUE
  
#r:
#  - oldrel
#  - release
#  - devel
  
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      r: release
            
    - os: osx
      osx_image: xcode10.2
      r: release
      env:
        - CC=clang
        - CXX=clang++

# from https://discourse.mc-stan.org/t/building-rstanarm-like-packagee-on-travis-with-c-14/6054/10?
before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
