# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false
r_build_args: '--no-build-vignettes'

after_success:
  - Rscript -e 'covr::codecov()'
  
env:
  - RGL_USE_NULL=TRUE
  
matrix:
  include:
    - dist: precise
      before_install:
        - sudo apt-get install libfreetype6-dev 
        - sudo apt-get install libftgl-dev
        - sudo apt-get install mesa-common-dev 
        - sudo apt-get install libglu1-mesa-dev
      r:
        - release
        - devel
        - oldrel
    - dist: trusty
      before_install:
        - sudo apt-get install libfreetype6-dev 
        - sudo apt-get install libftgl-dev
        - sudo apt-get install mesa-common-dev 
        - sudo apt-get install libglu1-mesa-dev
      r:
        - release
        - devel
        - oldrel
    - dist: xenial
      before_install:
        - sudo apt-get install libfreetype6-dev 
        - sudo apt-get install libftgl-dev
        - sudo apt-get install mesa-common-dev 
        - sudo apt-get install libglu1-mesa-dev
      r: release
    - dist: bionic
      before_install:
        - sudo apt-get install libfreetype6-dev 
        - sudo apt-get install libftgl-dev
        - sudo apt-get install mesa-common-dev 
        - sudo apt-get install libglu1-mesa-dev
      r:
        - release
        - devel
    - os: osx
      osx_image: xcode10.2
      r: release
    - os: osx
      osx_image: xcode9.4
      r: release
    - os: osx
      osx_image: xcode7.3
      r: release
  