# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  
r:
  - oldrel
  - release
  - devel
  
r_binary_packages:
  - rgl
    
env:
  - RGL_USE_NULL=TRUE
  
install:
- options(pkgType = "binary")
- R -e 'devtools::install_deps(dep = T)'